name: Build For Linux

on: [push]

jobs:
  linux:
    name: Linusx
    runs-on: ubuntu-latest

    steps:
      - name: Checkout sources
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          submodules: recursive

      - name: Install dependencies
        run: |
          sudo dpkg --add-architecture i386
          sudo apt update
          sudo apt install -y \
            build-essential \
            clang \
            cmake \
            gcc-multilib \
            g++-multilib \
            libc6-dev-i386 \
            libstdc++6:i386 \
            libgcc-12-dev:i386 \
            make

      - name: Build Project
        run: |
          cd project
          mkdir -p build
          cd build
          cmake .. -DCMAKE_BUILD_TYPE=Release
          make -j2

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ebot-linux
          path: project/build/ebot/ebot.so
