name: Build For Windows

on: [push]

env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

jobs:
  windows:
    name: Windows-ClangCL-32bit
    runs-on: windows-latest

    steps:
      - name: Checkout sources
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          submodules: recursive

      - name: Setup LLVM Clang
        uses: egor-tisin/setup-clang@v1
        with:
          version: 'latest'

      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v2
        with:
          vs-version: 'latest'

      - name: Build Project (Release)
        run: |
          cd project
          msbuild ebot.vcxproj /p:Configuration=EBOT_Release /p:Platform=Win32 /p:PlatformToolset=ClangCL /t:Clean,Build /m

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ebot-windows
          path: project/ebot_release/ebot.dll
